### ISSUE TITLE
Dublicate alias of HCG

### ISSUE THREAD

**Issue by acterhd** [scijs/color-space#15]
https://github.com/scijs/color-space/blob/master/hcg.js
```
alias: ['HCG', 'HST', 'HSG', 'HSW', 'HCV', 'HS2', 'HSV2', 'HST'],
```

HST, HST :)

**Comment by dfcreative** [comment]
Thank you.

**Comment by acterhd** [comment]
Also add HCT. 
I think T is tone, and means: Hue, Chroma, Tone.

**Comment by dfcreative** [comment]
Too many aliases for one space, I’m thinking to remove them at all as the space is not well known.

**Comment by acterhd** [comment]
Do not remove color space.
