### ISSUE TITLE
Cannot read property 'husl' of undefined

### ISSUE THREAD

**Issue by bigtimebuddy** [scijs/color-space#27]
The newer versions of **husl** (6.0.2+) are built using Haxe and no longer exposes private APIs. This package is broken when doing a `require('color-space')` because of the following line: https://github.com/scijs/color-space/blob/master/husl.js#L20. Could you please adjust to use only the public APIs?

The workaround is to require a specific module by name and not require the husl module, e.g., `require('color-space/rgb')`

**Comment by dfcreative** [comment]
@bigtimebuddy yes, that is recommended usage pattern (`require('color-space/<target-space>')`), because including the whole color-space will unreasonably bloat bundle.

But thanks for the issue.

**Comment by dfcreative** [comment]
Hm not sure how to fix that but sticking to `5.x` version, because public API now is flawed for color-space case.

**Comment by dfcreative** [comment]
Ok, fixed in _1.14.7_
