### ISSUE TITLE
Add HCG tests

### ISSUE THREAD

**Issue by acterhd** [scijs/color-space#9]
Please, wait. I will add support for HCG tests. How to it run? 
Okay. Try describe: 
```
hcg[0, 0.5, 1] == rgb[255, 128, 128]
hcg[0, 0.5, 0] == rgb[128, 0, 0]
hcg[0, 0.5, 0.5] == rgb[192, 64, 64]
hcg[0, 1, 0] == rgb[255, 0, 0]
hcg[0, 0, 0] == rgb[0, 0, 0]
hcg[0, 0, 1] == rgb[255, 255, 255]
hcg[0, 0.5, 1] == rgb[128, 128, 128]
```

If not working, try 127 number.

**Comment by dfcreative** [comment]
`npm test`

**Comment by dfcreative** [comment]
See https://github.com/scijs/color-space/blob/master/test/index.js for examples.

**Comment by acterhd** [comment]
I added tests

**Comment by dfcreative** [comment]
Try just cloning a new repo. There are updated mumath and added .gitignore.
